### ISSUE TITLE
Add a tooltip

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#13]
add a tooltip to the icon that displays the weather condition, so that users can see a text description of the condition when they hover over the icon.

**Comment by soumytiwari** [comment]
assign this to me :)

**Comment by ThanushaMandala** [comment]
done @soumytiwari

**Comment by soumytiwari** [comment]
Could you please unarchive your repository, if it is archived?
because, hacktoberfest isn't able to accept my PRs.. and you have used the
tag of "hacktoberfest" in your issue.
It says, there are many reasons it isn't possible, like the repo is
archived or the mantianer needs to approve your pull/merge request.

Could you please see it and help it be accepted by "hacktoberfest"?
